// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitialGatewayPage():Promise<void>;

export function InitialLoginPage():Promise<void>;

export function InitialRegisterPage():Promise<void>;
