// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitialGatewayPage() {
  return window['go']['initial']['Initial']['InitialGatewayPage']();
}

export function InitialLoginPage() {
  return window['go']['initial']['Initial']['InitialLoginPage']();
}

export function InitialRegisterPage() {
  return window['go']['initial']['Initial']['InitialRegisterPage']();
}
