// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CustomErrorDialog(arg1) {
  return window['go']['main']['App']['CustomErrorDialog'](arg1);
}

export function CustomInfoDialog(arg1) {
  return window['go']['main']['App']['CustomInfoDialog'](arg1);
}
