// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CustomErrorDialog(arg1:string):Promise<void>;

export function CustomInfoDialog(arg1:string):Promise<void>;
